### ISSUE TITLE
conditional wgan

### ISSUE THREAD

**Issue by tenoyart** [igul222/improved_wgan_training#29]
Could you release your source code of conditional WGAN-GP for cifar 10 (as shown in Figure 5 in your updated v2 manuscript)? Thanks.

**Comment by tenoyart** [comment]
Just curious if you are planning to release it or not. Thanks!

**Comment by igul222** [comment]
Sorry for the delay. We are planning on releasing code for that model soon.

________________________________

**Comment by tenoyart** [comment]
Great, thanks! Looking forward to that.
