### ISSUE TITLE
gradients = tf.gradients(disc_interpolates, [interpolates])[0]

### ISSUE THREAD

**Issue by YifanZuo** [igul222/improved_wgan_training#34]
gradients = tf.gradients(disc_interpolates, [interpolates])[0]  what does [0] mean at the end? I am really confused by this index. Thank you very much!

**Comment by igul222** [comment]
It's just because `tf.gradients` returns a list of gradients (we passed in a list of tensors to differentiate wrt), even though this list only has one element (since the list we passed in only had one element).
