### ISSUE TITLE
Potential inconsistencies in calculation of gradient penalty between code and ArXiv paper

### ISSUE THREAD

**Issue by wronk** [igul222/improved_wgan_training#39]
I could be wrong, but it seems like the calculation for the gradient penalty is not the same across different code examples in this repo. In the paper, I believe the calculation is shown in line 6 in Algorithm 1 (page 4 in ArXiv paper) -- that line suggests the second of the 2 options is correct. However, most code examples seem to use the first option below.

### Option 1
In `gan_mnist.py` (Line 143-144), `gan_64x64.py` (495-496), `gan_language.py` (104-105), `gan_cifar.py` (130-131), and `gan_cifar_resnet.py` (260-261:
```
differences = fake_data - real_data
interpolates = real_data + (alpha*differences)

# After rearranging, equivalent to: 
# real_data + alpha*fake_data - alpha*real_data
```

### Option 2
In `gan_toy.py` (Line 77) and ArXiv paper (Algorithm 1, line 6 on page 4):
```
interpolates = alpha*real_data + ((1-alpha)*fake_data)

# After rearranging, equivalent to: 
# fake_data + alpha*real_data - alpha*fake_data
```

`real_data` and `fake_data` seem to be transposed between the two options. Am I missing something?

**Comment by igul222** [comment]
You're right that they expand to different values, but when alpha is a random variable which varies uniformly between 0 and 1 the expressions are equivalent  :)

________________________________

**Comment by wronk** [comment]
Had to think about it a while, but I think I get it :) -- can you spot check this geometric interpretation? 

Basically, the `differences` vector goes from the `real_data` to the `fake_data`. Because you're adding on a random proportion of this vector to the `real_data`, you're essentially getting some random point on the line between the `real_data` and `fake_data` vectors. And because it's random between 0 and 1, it doesn't matter if you instead start from `fake_data` and traverse towards `real_data` -- you'll still end up at some random point on the line between the two.

**Comment by igul222** [comment]
Correct!

________________________________

**Comment by wronk** [comment]
Cool, thanks
