### ISSUE TITLE
Inconsistency in interpolation.

### ISSUE THREAD

**Issue by apisarek** [igul222/improved_wgan_training#40]
Hi! Awesome work :)

I've noticed that in all files (but no in `gan_toy.py`) you use `interpolates = real_data + (alpha*differences)` but not `interpolates = (1-alpha)*real_data + (alpha*differences)`. I don't know if results in paper where trained with that inconsistency or if it changes something, but I just wanted to mention it and ask if this is a bug or not.

**Comment by igul222** [comment]
They're exactly equivalent when alpha is drawn from U[0,1]

________________________________

**Comment by apisarek** [comment]
Oh, sure, I've mistaken `differences` with `fake_data` somehow. Thank you for quick response.

**Comment by apisarek** [comment]
Oh, sure, I've mistaken `differences` with `fake_data` somehow. Thank you for quick response.
