### ISSUE TITLE
Is the output normal?

### ISSUE THREAD

**Issue by kingofoz** [igul222/improved_wgan_training#5]
Hi @igul222 
Please see the output from the command of "python gan_toy.py":
iter 99	disc cost	-0.811114370823
iter 199	disc cost	-0.382090866566
iter 299	disc cost	-0.788745164871
iter 399	disc cost	-1.34008586407
iter 499	disc cost	-1.38578748703
iter 599	disc cost	-1.25771450996
iter 699	disc cost	-1.0593495369
iter 799	disc cost	-0.865160703659
iter 899	disc cost	-0.686692357063
iter 999	disc cost	-0.57303828001
iter 1099	disc cost	-0.454357266426

You see, the disc cost is minus, is this normal?

Thanks,
Yingjun

**Comment by martinarjovsky** [comment]
You have to plot -disc cost! That's the Wasserstein :)

**Comment by igul222** [comment]
What Martin said :) this output seems fine to me.

**Comment by kingofoz** [comment]
Got it. Thank you, both of you. 👍
