### ISSUE TITLE
Use different generated fake images to calculate D_loss and G_loss?

### ISSUE THREAD

**Issue by watsonyanghx** [igul222/improved_wgan_training#53]
I see when calculating D_loss, you use the fake images generated by this [https://github.com/igul222/improved_wgan_training/blob/master/gan_cifar_resnet.py#L192](https://github.com/igul222/improved_wgan_training/blob/master/gan_cifar_resnet.py#L192) , but when calculating the G_loss, you use another generated images by this [https://github.com/igul222/improved_wgan_training/blob/master/gan_cifar_resnet.py#L293](https://github.com/igul222/improved_wgan_training/blob/master/gan_cifar_resnet.py#L293) .

Since I'm new to GAN and this is not the same as other implementations, could anyone tell me if this implementation (use different generated fake images to calculate D_loss and G_loss) is right? And what's the difference between them?

**Comment by igul222** [comment]
Both sets of images are random draws from the same generator; i.e. they can be considered samples from the same distribution. The difference is that when we update the generator, we use 2x the batch size because this speeds up convergence a little.
