### ISSUE TITLE
interpolates in wgan-gp

### ISSUE THREAD

**Issue by Willjay90** [igul222/improved_wgan_training#54]
I'm following **Algorithm 1** in the [paper](https://arxiv.org/pdf/1704.00028.pdf) with MNIST dataset. 
```
x ̃ ← G θ ( z )
xˆ ← εx + (1 − ε)x ̃
```
However, in the [code](https://github.com/igul222/improved_wgan_training/blob/master/gan_mnist.py), it shows
```
differences = fake_data - real_data
interpolates = real_data + (alpha*differences)
             = read_data + alpha*(fake_data - real_data) 
             = alpha * fake_data + (1-alpha) * real_data
```
why?

**Comment by pierremac** [comment]
Well, set alpha = 1 - epsilon and I guess you get the result!
And as alpha is set to be sampled uniformly at random between 0 and 1, so is epsilon.
