### ISSUE TITLE
The data for LSUN bedrooms.

### ISSUE THREAD

**Issue by biuyq** [igul222/improved_wgan_training#56]
I just noticed that the data you provided in issue #30 is a "ILSVRC2012_128.tar" one but not the bedrooms images. Could you please provide the images that you use for reproducing the bedroom results in your paper?

**Comment by martinarjovsky** [comment]
Our bad, this is the correct one! https://s3.amazonaws.com/ishaan-misc/lsun_128_train.tar.gz
