### ISSUE TITLE
The results for LSUN bedrooms 128*128.

### ISSUE THREAD

**Issue by biuyq** [igul222/improved_wgan_training#57]
I found your code used by training the LSUN bedrooms128*128 in your paper, but cannot reproduce the results. The data link in your issue #30 is a  "ILSVRC2012_128.tar" one but not the bedrooms images. I'm wondering what data pre-processing you used in the original LSUN bedrooms dataset? Mine is just use center clip [center-64,center+64] as most paper did. BTW, did you you the whole LSUN bedroom dataset for training? Could you please provide the images or the detailed pre-processing method that you use for reproducing the bedroom results in your paper? Thanks so much!

**Comment by martinarjovsky** [comment]
Hi! Here are the images we used https://s3.amazonaws.com/ishaan-misc/lsun_128_train.tar.gz .

@igul222 might comment if there's more preprocessing required but I don't think so.  Just replacing the tar in https://github.com/igul222/improved_wgan_training/issues/30 by this one should work.

If you have any more problems let us know! If you reproduce without problems also let us know if you can :P

Thanks!
Martin

**Comment by biuyq** [comment]
@martinarjovsky  Thx so much！

**Comment by biuyq** [comment]
Thanks for sharing your data, I can reproduce your work! The difference is that I just used 128by128  window for cutting the original LSUN, your is a 256by256 window then resize into 128by128. Thanks for your help!

**Comment by martinarjovsky** [comment]
Awesome! Thanks for letting us know :)
