### ISSUE TITLE
Poor results in WGAN mode on CelebA

### ISSUE THREAD

**Issue by eitanrich** [igul222/improved_wgan_training#59]
Hi,

I'm trying to train on CelebA (cropped and resized to 64x64).
The results in WGAN-GP mode look great, both in quality and diversity, however, when I set the mode to 'wgan', I get very distorted faces even after 200K iterations.
Any ideas?

![celeba_samples_102799](https://user-images.githubusercontent.com/29534333/35486936-376aa222-047e-11e8-8d42-c24e1470479e.png)

Thanks,
Eitan

**Comment by igul222** [comment]
Which architecture?

________________________________

**Comment by eitanrich** [comment]
I'm not sure it answers your question, but I used the default GoodGenerator, GoodDiscriminator, with the following parameters:

MODE = 'wgan' # dcgan, wgan, wgan-gp, lsgan
DIM = 64 # Model dimensionality
CRITIC_ITERS = 5 # How many iterations to train the critic for
N_GPUS = 2 # Number of GPUs
BATCH_SIZE = 64 # Batch size. Must be a multiple of N_GPUS
ITERS = 200000 # How many iterations to train for
LAMBDA = 10 # Gradient penalty lambda hyperparameter
OUTPUT_DIM = 64*64*3 # Number of pixels in each iamge

**Comment by eitanrich** [comment]
The same configuration with MODE = 'wgan-gp' produces nice results, without the distortions.
Eitan

**Comment by igul222** [comment]
GoodGenerator is only tested with WGAN-GP. If you want to use other gans it's recommended to use the DcganGenerator / DcganDiscriminator.

________________________________

**Comment by eitanrich** [comment]
Thanks. This seems to be working.

**Comment by y601757692l** [comment]
hi,now i am also trying to train on CelebA (cropped and resized to 64x64)  in WGAN-GP mode . I just modify the DATA_DIR in gan_64x64.py. But there was a mistake like this：
IOError: [Errno 2] No such file or directory: '/data-4T-B/yelu/data/dcgan-completion.tensorflow/aligned/img_align_celeba_png/train_64x64/train_64x64/0927649.png'
Could you show me your code? thanks so much~~~
