### ISSUE TITLE
 train on CelebA (cropped and resized to 64x64) in WGAN-GP mode

### ISSUE THREAD

**Issue by y601757692l** [igul222/improved_wgan_training#61]
hi,now i am also trying to train on CelebA (cropped and resized to 64x64) in WGAN-GP mode . I just modify the DATA_DIR in gan_64x64.py. But there was a mistake like this：
IOError: [Errno 2] No such file or directory: '/data-4T-B/yelu/data/dcgan-completion.tensorflow/aligned/img_align_celeba_png/train_64x64/train_64x64/0927649.png'
Could you  show me your code? thanks so much~~~

**Comment by dinggd** [comment]
It clearly shows that file path does not lead to a file. Check your DATA_DIR variables, chances are it is not properly set.

**Comment by y601757692l** [comment]
thank you so much
