### ISSUE TITLE
When do you start seeing positive results?

### ISSUE THREAD

**Issue by meder411** [igul222/improved_wgan_training#62]
I notice that on CIFAR, for example, you train for 200k generator iterations. Surely you start seeing positive results (i.e. realistic images) well before then. Around how many generator iterations into training can you tell that the network is moving in the right direction (i.e. generator outputs are looking more and more realistic)?

**Comment by igul222** [comment]
Depends on your personal definition of "realistic" but I can usually tell if things are going to work out within 1000 iterations.
