### ISSUE TITLE
inception_score.py: ValueError in the method _init_inception()

### ISSUE THREAD

**Issue by psanch21** [igul222/improved_wgan_training#82]
I am getting the following error in the method _init_inception() after fixing
    `o.set_shape(tf.TensorShape(new_shape))`
The error is
    `ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [2048], [2048,1008].`
 
which is in line 93
         `logits = tf.matmul(tf.squeeze(pool3), w)`

**Comment by Oreobird** [comment]
`logits= tf.matmul(tf.squeeze(pool3, [1, 2]), w)` 
works for me
