### ISSUE TITLE
reproducing inception score on gan_cifar.py

### ISSUE THREAD

**Issue by vibss2397** [igul222/improved_wgan_training#92]
Hi, I am trying to reproduce the figure in the paper for inception score. After running your repository these are the results i get.

![inception_score](https://user-images.githubusercontent.com/22891797/100768515-f9104180-33c8-11eb-86a0-783629e0bf31.jpg)

Sure its reaching the score of 6 as shown in the paper, but it's not the same. So my question is does the random seed also matter, or was that figure the best you got after you ran a bunch of experiments.

**Comment by igul222** [comment]
Looks like the same plot as the paper to me (https://arxiv.org/pdf/1704.00028.pdf Figure 3, left subplot, orange line). Note that the axis scales are different here.

**Comment by vibss2397** [comment]
yeah close enough, actually I am trying to make an implementation in pytorch for this script and the inception score and so far with different initializations provided by pytorch I have been able to reach 5.6 score max. However, I have saved the weights you used in this script and hopefully i should reach up to 6. Thanks :)
